# Generated by Django 5.2.8 on 2025-11-29 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SerialKiller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(db_index=True, help_text='Common name or nickname', max_length=255)),
                ('full_name', models.CharField(blank=True, help_text='Full legal name', max_length=255, null=True)),
                ('aliases', models.TextField(blank=True, help_text='Known aliases or other names', null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, help_text='Primary country associated', max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('proven_victims', models.CharField(blank=True, help_text="Number of proven victims (e.g., '17' or '100+')", max_length=50, null=True)),
                ('possible_victims', models.CharField(blank=True, help_text='Possible victim count', max_length=50, null=True)),
                ('years_active', models.CharField(blank=True, help_text="Years active (e.g., '1974-1978')", max_length=100, null=True)),
                ('active_countries', models.TextField(blank=True, help_text='Countries where crimes occurred', null=True)),
                ('modus_operandi', models.TextField(blank=True, help_text='Method of operation', null=True)),
                ('capture_date', models.DateField(blank=True, null=True)),
                ('sentence', models.TextField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('manner_of_death', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, help_text='Current status (e.g., Executed, Imprisoned)', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Serial Killer',
                'verbose_name_plural': 'Serial Killers',
                'db_table': 'Serial Killers',
                'ordering': ['common_name'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(help_text='Common name or nickname', max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('aliases', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('birth_country', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('proven_victims', models.CharField(blank=True, max_length=50, null=True)),
                ('possible_victims', models.CharField(blank=True, max_length=50, null=True)),
                ('years_active', models.CharField(blank=True, max_length=100, null=True)),
                ('active_countries', models.TextField(blank=True, null=True)),
                ('modus_operandi', models.TextField(blank=True, null=True)),
                ('capture_date', models.DateField(blank=True, null=True)),
                ('sentence', models.TextField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('manner_of_death', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('submission_status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('finished', 'Finished')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Suggestion',
                'verbose_name_plural': 'Suggestions',
                'db_table': 'Suggestions',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_text', models.TextField(help_text='Correction or modification details')),
                ('submission_status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('finished', 'Finished')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('killer', models.ForeignKey(db_column='killer_id', help_text='Serial killer this modification is about', on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='killers.serialkiller')),
            ],
            options={
                'verbose_name': 'Modification',
                'verbose_name_plural': 'Modifications',
                'db_table': 'Modifications',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
