# Generated by Django 5.2.8 on 2025-11-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('killers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serialkiller',
            name='country',
        ),
    ]
