# Generated by Django 5.2.8 on 2025-11-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killers', '0002_remove_serialkiller_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialkiller',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serialkiller',
            name='status',
            field=models.CharField(blank=True, choices=[('Imprisoned', 'Imprisoned'), ('Deceased', 'Deceased'), ('At Large', 'At Large'), ('Released', 'Released'), ('Unknown', 'Unknown')], help_text='Current status (e.g., Executed, Imprisoned)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Unknown', 'Unknown')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='status',
            field=models.CharField(blank=True, choices=[('Imprisoned', 'Imprisoned'), ('Deceased', 'Deceased'), ('At Large', 'At Large'), ('Released', 'Released'), ('Unknown', 'Unknown')], max_length=100, null=True),
        ),
    ]
