# Generated by Django 5.2.8 on 2025-11-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killers', '0003_alter_serialkiller_gender_alter_serialkiller_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialkiller',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='serialkiller',
            name='proven_victims',
            field=models.PositiveIntegerField(blank=True, help_text='Number of proven victims', null=True),
        ),
        migrations.AlterField(
            model_name='serialkiller',
            name='status',
            field=models.CharField(blank=True, choices=[('imprisoned', 'Imprisoned'), ('deceased', 'Deceased'), ('at_large', 'At Large'), ('released', 'Released'), ('unknown', 'Unknown')], help_text='Current status (e.g., Executed, Imprisoned)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('unknown', 'Unknown')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='proven_victims',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='status',
            field=models.CharField(blank=True, choices=[('imprisoned', 'Imprisoned'), ('deceased', 'Deceased'), ('at_large', 'At Large'), ('released', 'Released'), ('unknown', 'Unknown')], max_length=100, null=True),
        ),
    ]
