# Generated by Django 5.2.8 on 2025-12-01 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('killers', '0004_alter_serialkiller_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Admin assigned to review this modification', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_modifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serialkiller',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Admin assigned to manage this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_killers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Admin assigned to review this suggestion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_suggestions', to=settings.AUTH_USER_MODEL),
        ),
    ]
